// <auto-generated />
namespace Com.Pinz.Server.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_PinzSuperadmin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_PinzSuperadmin));
        
        string IMigrationMetadata.Id
        {
            get { return "201603181516170_User_PinzSuperadmin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
