// <auto-generated />
namespace Com.Pinz.Server.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Subsciption_OriginalEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Subsciption_OriginalEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201611151426575_Subsciption_OriginalEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
