// <auto-generated />
namespace Com.Pinz.Server.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Password : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Password));
        
        string IMigrationMetadata.Id
        {
            get { return "201603162139198_User_Password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
